# Which languages should be cached?
#
# The following must be an existing
# lang file in the "lang" folder
lang:
  - en.yml

# # # # # # # # # #
# COMMANDS        #
# # # # # # # # # #
commands:
  ReloadSubCommand:
    Permission: "quests.reload"
  ResetSubCommand:
    Permission: "quests.reset"
  AddSubCommand:
    Permission: "quests.add"
  JoinSubCommand:
    Permission: "quests.join"
  LeaveSubCommand:
    Permission: "quests.leave"
  StatusSubCommand:
    Permission: "quests.status"
  MenuSubCommand:
    Permission: "quests.menu"
  LanguageSubCommand:
    Permission: "quests.language"

mysql:
  Host: localhost
  Port: 3306
  Username: root
  Password: Feel4-Probation6-Untagged2-Slicing1
  Database: test