# Which languages should be cached?
#
# The following must be an existing
# lang file in the "lang" folder
lang:
  - en.yml

# If this is set to true, then when
# a player executes the configured
# quests command, it will automatically
# open the quests' menu.
#
# If false, then all commands will
# be displayed in the chat
DisplayMenuWhenNoArguments: false

# # # # # # # # # #
# COMMANDS        #
# # # # # # # # # #
commands:
  ReloadSubCommand:
    Permission: "quests.reload"
  ResetSubCommand:
    Permission: "quests.reset"
  AddSubCommand:
    Permission: "quests.add"
  DeleteSubCommand:
    Permission: "quests.delete"
  StatusSubCommand:
    Permission: "quests.status"
  MenuSubCommand:
    Permission: "quests.menu"
  LanguageSubCommand:
    Permission: "quests.language"

mysql:
  Host: localhost
  Port: 3306
  Username: root
  Password: Feel4-Probation6-Untagged2-Slicing1
  Database: test