# Which languages should be cached?
#
# The following must be an existing
# lang file in the "lang" folder
#
# WARNING: DO NOT REMOVE THE en.yml
# file! It acts as a default is there
# are no languages configured
lang:
  - en.yml

# If this is set to true, then when
# a player executes the configured
# quests command, it will automatically
# open the quests' menu.
#
# If false, then all commands will
# be displayed in the chat
DisplayMenuWhenNoArguments: false

# How many quests should be pulled
# from the total quests pull when
# the quests are reset
RandomizedPoolAmount: 3

# # # # # # # # # #
# COMMANDS        #
# # # # # # # # # #
commands:
  ResetSubCommand:
    Permission: "quests.reset"
  AddSubCommand:
    Permission: "quests.add"
  DeleteSubCommand:
    Permission: "quests.delete"
  MenuSubCommand:
    Permission: "quests.menu"
  LanguageSubCommand:
    Permission: "quests.language"

mysql:
  Host: localhost
  Port: 3306
  Username: root
  Password: Feel4-Probation6-Untagged2-Slicing1
  Database: test