name: Quests
version: ${project.version}
author: CodePunisher
main: lol.arch.quests.QuestsPlugin
depend: [ store-spigot, cloudsync ]
softdepend: [ PlaceholderAPI ]
api-version: 1.20
libraries:
  - dev.dejvokep:boosted-yaml:1.3